#!/usr/bin/env python3
"""
generate_pptx_template.py — create a new .pptx template for the PPTX
generation service (Theme Engine edition).

What is a "template" now?
-------------------------
The generator service (app/services/pptx_gen.py) renders decks fully
programmatically and only needs a *theme* (palette + fonts).  A template
file is therefore a THEME CARRIER:

  * it is what the Workspace UI lists, thumbnails, and lets users upload
  * at generation time the service extracts its colours/fonts
    (theme1.xml + master background) and feeds the same bullet-proof
    renderer — the template's XML never enters a generated deck.

This script builds such a carrier:

  * 16:9 widescreen (13.33" x 7.5"), 0 slides, 11 stock layouts
  * full theme1.xml colour scheme (dk1/lt1/dk2/lt2/accent1-6/hyperlinks)
    and font scheme (major/minor latin typefaces)
  * slide-master + every layout background set to the theme bg
  * layout 0 (Title Slide) styled with the same decorative language the
    renderer uses (accent bar / circles / frame) so the schematic
    thumbnail generated by the Workspace matches the real output
  * Windows printerSettings blob stripped (repair-prompt hygiene)

Usage:
    # regenerate one of the shipped themes
    python3 scripts/generate_pptx_template.py --preset corporate

    # fully custom theme
    python3 scripts/generate_pptx_template.py \
        --name startup \
        --bg 0F1B2D --fg E8EEF5 --title FFFFFF \
        --accent 2D7DD6 --accent2 F26430 \
        --font-title Calibri --font-body Calibri \
        --decor bars \
        --out app/templates/pptx

Requires: python-pptx (already a project dependency).
"""

from __future__ import annotations

import argparse
import re
import shutil
import zipfile
from pathlib import Path

from lxml import etree
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn
from pptx.util import Emu, Inches, Pt

# 16:9 widescreen slide size.
WIDESCREEN_W = Emu(12192000)  # 13.333 inches
WIDESCREEN_H = Emu(6858000)  # 7.5    inches

A_NS = "http://schemas.openxmlformats.org/drawingml/2006/main"

# Palettes mirroring the in-code built-in themes of app/services/pptx_gen.py,
# so regenerated template files match what the renderer actually draws.
PRESETS = {
    "corporate": dict(
        bg="0F2740",
        fg="C7D3E2",
        title="FFFFFF",
        accent="F2A33C",
        accent2="3E7CB1",
        font_title="Calibri",
        font_body="Calibri",
        decor="bars",
    ),
    "modern": dict(
        bg="FFFFFF",
        fg="3C4A48",
        title="0E3A36",
        accent="0D9488",
        accent2="F97316",
        font_title="Trebuchet MS",
        font_body="Calibri",
        decor="circles",
    ),
    "elegant": dict(
        bg="251B33",
        fg="CFC4DE",
        title="F3ECD9",
        accent="D4AF37",
        accent2="8E7CC3",
        font_title="Georgia",
        font_body="Georgia",
        decor="frame",
    ),
}


def _hex_to_rgb(hex_str: str) -> RGBColor:
    s = hex_str.lstrip("#").strip()
    if not re.fullmatch(r"[0-9A-Fa-f]{6}", s):
        raise ValueError(f"invalid hex color: {hex_str!r} (expected RRGGBB)")
    return RGBColor(int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))


def _lum(c: RGBColor) -> float:
    return (0.299 * int(c[0]) + 0.587 * int(c[1]) + 0.114 * int(c[2])) / 255.0


def _blend(c1: RGBColor, c2: RGBColor, t: float) -> RGBColor:
    t = max(0.0, min(1.0, t))
    return RGBColor(
        int(round(int(c1[0]) * t + int(c2[0]) * (1 - t))),
        int(round(int(c1[1]) * t + int(c2[1]) * (1 - t))),
        int(round(int(c1[2]) * t + int(c2[2]) * (1 - t))),
    )


def _hx(c: RGBColor) -> str:
    return f"{int(c[0]):02X}{int(c[1]):02X}{int(c[2]):02X}"


# ── theme1.xml rewriting ─────────────────────────────────────────────


def _rewrite_theme(
    theme_part,
    *,
    bg: RGBColor,
    fg: RGBColor,
    title: RGBColor,
    accent: RGBColor,
    accent2: RGBColor,
    font_title: str,
    font_body: str,
) -> None:
    """Rewrite the theme part's colour + font schemes in place.

    We set theme_part._blob — python-pptx keeps the theme as a generic
    Part and serializes exactly this blob on save.
    """
    tree = etree.fromstring(theme_part.blob)
    dark = _lum(bg) < 0.45

    # ── Colour scheme ──
    # dk1/lt1 keep standard semantics (dark/light anchors).  The master
    # background carries the actual bg; extraction prefers it.
    dk1 = fg if not dark else _hex_to_rgb("000000")
    lt1 = _hex_to_rgb("FFFFFF") if dark else bg
    dk2 = _blend(title, bg, 0.85)
    lt2 = _blend(bg, fg, 0.10)
    scheme = {
        "dk1": _hx(dk1),
        "lt1": _hx(lt1),
        "dk2": _hx(dk2),
        "lt2": _hx(lt2),
        "accent1": _hx(accent),
        "accent2": _hx(accent2),
        "accent3": _hx(_blend(accent2, bg, 0.8)),
        "accent4": _hx(_blend(accent, _hex_to_rgb("FFFFFF"), 0.45)),
        "accent5": _hx(_blend(accent, bg, 0.55)),
        "accent6": _hx(_blend(accent2, _hex_to_rgb("FFFFFF"), 0.5)),
        "hlink": _hx(accent),
        "folHlink": _hx(accent2),
    }
    clr = tree.find(f".//{{{A_NS}}}clrScheme")
    if clr is None:
        raise RuntimeError("theme1.xml has no clrScheme")
    for tag, val in scheme.items():
        el = clr.find(f"{{{A_NS}}}{tag}")
        if el is None:
            continue
        # remove existing colour children, then add a clean srgbClr
        for child in list(el):
            el.remove(child)
        srgb = etree.SubElement(el, f"{{{A_NS}}}srgbClr")
        srgb.set("val", val)

    # ── Font scheme ──
    for tag, typeface in (("majorFont", font_title), ("minorFont", font_body)):
        el = tree.find(f".//{{{A_NS}}}{tag}")
        if el is None:
            continue
        latin = el.find(f"{{{A_NS}}}latin")
        if latin is None:
            latin = etree.Element(f"{{{A_NS}}}latin")
            el.insert(0, latin)
        latin.set("typeface", typeface)

    theme_part._blob = etree.tostring(
        tree, xml_declaration=True, encoding="UTF-8", standalone=True
    )


# ── background / placeholder styling ─────────────────────────────────


def _apply_background(slide_or_layout, bg: RGBColor) -> None:
    cSld = slide_or_layout._element.find(qn("p:cSld"))
    if cSld is None:
        return
    for old in cSld.findall(qn("p:bg")):
        cSld.remove(old)
    bg_el = etree.SubElement(cSld, qn("p:bg"))
    bgPr = etree.SubElement(bg_el, qn("p:bgPr"))
    fill = etree.SubElement(bgPr, qn("a:solidFill"))
    srgb = etree.SubElement(fill, qn("a:srgbClr"))
    srgb.set("val", _hx(bg))
    etree.SubElement(bgPr, qn("a:effectLst"))
    cSld.insert(0, bg_el)  # schema order: p:bg is first child of p:cSld


def _style_placeholder_text(
    ph, color: RGBColor, size_pt: int, bold: bool = False
) -> None:
    """Set font colour/size/bold on a placeholder's runs AND defRPr.

    Schema-safe: <a:pPr> is created as the FIRST child of <a:p> (before
    any runs), matching the CT_TextParagraph sequence.
    """
    if not ph.has_text_frame:
        return
    tf = ph.text_frame
    for para in tf.paragraphs:
        for run in para.runs:
            run.font.color.rgb = color
            run.font.size = Pt(size_pt)
            run.font.bold = bold
        p = para._p
        pPr = p.find(qn("a:pPr"))
        if pPr is None:
            pPr = etree.Element(qn("a:pPr"))
            p.insert(0, pPr)  # FIRST child — schema order
        for old in pPr.findall(qn("a:defRPr")):
            pPr.remove(old)
        defRPr = etree.SubElement(pPr, qn("a:defRPr"))
        defRPr.set("sz", str(size_pt * 100))
        if bold:
            defRPr.set("b", "1")
        fill = etree.SubElement(defRPr, qn("a:solidFill"))
        srgb = etree.SubElement(fill, qn("a:srgbClr"))
        srgb.set("val", _hx(color))


def _layout_add_shape(prs, layout, shape_type, x, y, w, h):
    """
    Add a regular shape to a SlideLayout.

    python-pptx does not expose add_shape() on LayoutShapes.
    We temporarily create the shape on a slide, move its XML into
    the layout, and then remove the temporary slide.
    """
    slide = prs.slides.add_slide(layout)

    shape = slide.shapes.add_shape(shape_type, x, y, w, h)

    # Find an ID that is unique inside the layout.
    sp_tree = layout.shapes._spTree
    existing_ids = []

    for el in sp_tree.iter():
        value = el.get("id")
        if value and value.isdigit():
            existing_ids.append(int(value))

    next_id = max(existing_ids, default=1) + 1

    shape._element.xpath(".//p:cNvPr")[0].set("id", str(next_id))

    # Move the shape XML from the temporary slide to the layout.
    sp = shape._element
    sp.getparent().remove(sp)
    sp_tree.append(sp)

    # Remove the temporary slide.
    slide_id = prs.slides._sldIdLst[-1]
    prs.slides._sldIdLst.remove(slide_id)

    return shape


def _add_rect(prs, layout, x, y, w, h, color: RGBColor):
    shape = _layout_add_shape(
        prs,
        layout,
        MSO_SHAPE.RECTANGLE,
        x,
        y,
        w,
        h,
    )
    shape.shadow.inherit = False
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()
    return shape


def _add_ellipse(prs, layout, x, y, d, color: RGBColor):
    shape = _layout_add_shape(
        prs,
        layout,
        MSO_SHAPE.OVAL,
        x,
        y,
        d,
        d,
    )
    shape.shadow.inherit = False
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()
    return shape


def _style_title_layout(
    prs,
    layout,
    *,
    bg: RGBColor,
    title: RGBColor,
    fg: RGBColor,
    accent: RGBColor,
    accent2: RGBColor,
    decor: str,
) -> None:
    """Decorate layout 0 so schematic thumbnails mirror the renderer's look."""
    _apply_background(layout, bg)
    soft = _blend(accent, bg, 0.22)
    soft2 = _blend(accent2, bg, 0.16)
    faint = _blend(accent, bg, 0.12)

    if decor == "frame":
        # Thin accent frame + centered title.
        frame = _layout_add_shape(
            prs,
            layout,
            MSO_SHAPE.RECTANGLE,
            Inches(0.42),
            Inches(0.42),
            WIDESCREEN_W - Inches(0.84),
            WIDESCREEN_H - Inches(0.84),
        )
        frame.shadow.inherit = False
        frame.fill.background()
        frame.line.color.rgb = accent
        frame.line.width = Pt(1.25)
    elif decor == "circles":
        _add_ellipse(prs, layout, Inches(9.7), Inches(-1.5), Inches(5.4), faint)
        _add_ellipse(prs, layout, Inches(11.15), Inches(0.65), Inches(1.15), accent2)
        _add_ellipse(prs, layout, Inches(-0.9), Inches(5.6), Inches(2.4), soft)
    else:  # bars
        _add_rect(prs, layout, 0, 0, Inches(0.28), WIDESCREEN_H, accent)
        _add_ellipse(prs, layout, Inches(10.4), Inches(4.6), Inches(3.6), soft)
        _add_ellipse(prs, layout, Inches(11.6), Inches(3.7), Inches(1.5), soft2)

    for ph in layout.placeholders:
        idx = ph.placeholder_format.idx
        ptype = str(ph.placeholder_format.type)
        if idx == 0 or "TITLE" in ptype or "CENTER_TITLE" in ptype:
            _style_placeholder_text(ph, title, 44, bold=True)
        elif idx == 1 or "BODY" in ptype or "SUBTITLE" in ptype:
            _style_placeholder_text(ph, fg, 20)


# ── printerSettings strip ────────────────────────────────────────────


def _strip_printer_settings(path: Path) -> None:
    PRINTER_REL = (
        "http://schemas.openxmlformats.org/officeDocument/2006/"
        "relationships/printerSettings"
    )
    REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
    CT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"

    tmp = path.with_suffix(path.suffix + ".tmp")
    with zipfile.ZipFile(path, "r") as zin:
        with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if "printerSettings" in item.filename:
                    continue
                data = zin.read(item.filename)
                if item.filename == "ppt/_rels/presentation.xml.rels":
                    tree = etree.fromstring(data)
                    for rel in list(tree.findall(f"{{{REL_NS}}}Relationship")):
                        if rel.get("Type") == PRINTER_REL:
                            tree.remove(rel)
                    data = etree.tostring(
                        tree,
                        xml_declaration=True,
                        encoding="UTF-8",
                        standalone=True,
                    )
                elif item.filename == "[Content_Types].xml":
                    tree = etree.fromstring(data)
                    for d in list(tree.findall(f"{{{CT_NS}}}Default")):
                        if d.get("Extension") == "bin":
                            tree.remove(d)
                    data = etree.tostring(
                        tree,
                        xml_declaration=True,
                        encoding="UTF-8",
                        standalone=True,
                    )
                zout.writestr(item, data)
    shutil.move(str(tmp), str(path))


# ── main build ───────────────────────────────────────────────────────


def generate_template(
    name: str,
    bg_hex: str,
    fg_hex: str,
    title_hex: str,
    accent_hex: str,
    accent2_hex: str,
    font_title: str,
    font_body: str,
    decor: str,
    out_dir: Path,
) -> Path:
    """Build a themed .pptx template carrier and write {out_dir}/{name}.pptx."""
    bg = _hex_to_rgb(bg_hex)
    fg = _hex_to_rgb(fg_hex)
    title = _hex_to_rgb(title_hex) if title_hex else fg
    accent = _hex_to_rgb(accent_hex)
    accent2 = _hex_to_rgb(accent2_hex) if accent2_hex else accent

    prs = Presentation()
    prs.slide_width = WIDESCREEN_W
    prs.slide_height = WIDESCREEN_H

    master = prs.slide_masters[0]
    _apply_background(master, bg)

    for i, layout in enumerate(prs.slide_layouts):
        if i == 0:
            # Layout 0 carries the decorative identity (thumbnails).
            _style_title_layout(
                prs,
                layout,
                bg=bg,
                title=title,
                fg=fg,
                accent=accent,
                accent2=accent2,
                decor=decor,
            )
            continue
        _apply_background(layout, bg)
        for ph in layout.placeholders:
            idx = ph.placeholder_format.idx
            ptype = str(ph.placeholder_format.type)
            if idx == 0 or "TITLE" in ptype or "CENTER_TITLE" in ptype:
                _style_placeholder_text(ph, title, 32, bold=True)
            elif idx == 1 or "BODY" in ptype or "SUBTITLE" in ptype:
                _style_placeholder_text(ph, fg, 20)

    # theme1.xml: full colour + font scheme rewrite.
    theme_part = None
    for rel in master.part.rels.values():
        if rel.reltype.endswith("/theme"):
            theme_part = rel.target_part
            break
    if theme_part is None:
        raise RuntimeError("could not locate the theme part")
    _rewrite_theme(
        theme_part,
        bg=bg,
        fg=fg,
        title=title,
        accent=accent,
        accent2=accent2,
        font_title=font_title,
        font_body=font_body,
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{name}.pptx"
    prs.save(str(out_path))
    _strip_printer_settings(out_path)
    return out_path


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate a themed .pptx template (theme carrier) for use_pptx_gen.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--name",
        default=None,
        help="Template slug (becomes the filename: {name}.pptx). "
        "Required unless --preset is used.",
    )
    p.add_argument(
        "--preset",
        choices=sorted(PRESETS),
        default=None,
        help="Use one of the shipped theme palettes " "(corporate / modern / elegant).",
    )
    p.add_argument("--accent", default="3D8BFD", help="Accent colour, hex RRGGBB.")
    p.add_argument(
        "--accent2",
        default=None,
        help="Secondary accent, hex RRGGBB (defaults to --accent).",
    )
    p.add_argument(
        "--bg", default="FFFFFF", help="Slide background colour, hex RRGGBB."
    )
    p.add_argument(
        "--fg", default="333333", help="Default body text colour, hex RRGGBB."
    )
    p.add_argument(
        "--title-color",
        default=None,
        help="Title text colour, hex RRGGBB (defaults to --fg).",
    )
    p.add_argument(
        "--font-title", default="Calibri", help="Theme major (heading) latin typeface."
    )
    p.add_argument(
        "--font-body", default="Calibri", help="Theme minor (body) latin typeface."
    )
    p.add_argument(
        "--decor",
        choices=["bars", "circles", "frame"],
        default="bars",
        help="Decorative style used on the title layout "
        "(drives the schematic thumbnail).",
    )
    p.add_argument(
        "--out",
        default=None,
        help="Output directory (defaults to backend/app/templates/pptx).",
    )
    args = p.parse_args(argv)

    if args.preset:
        cfg = dict(PRESETS[args.preset])
        if args.name is None:
            args.name = args.preset
    else:
        cfg = dict(
            accent=args.accent,
            accent2=args.accent2,
            bg=args.bg,
            fg=args.fg,
            title=args.title_color,
            font_title=args.font_title,
            font_body=args.font_body,
            decor=args.decor,
        )

    if not args.name:
        p.error("--name is required unless --preset is given")
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", args.name):
        p.error("--name must be a lowercase slug (letters, digits, -, _)")

    # CLI flags override preset values when explicitly provided.
    hex_args = {
        "accent": args.accent,
        "accent2": args.accent2,
        "bg": args.bg,
        "fg": args.fg,
        "title": args.title_color,
    }
    defaults = {
        "accent": "3D8BFD",
        "accent2": None,
        "bg": "FFFFFF",
        "fg": "333333",
        "title": None,
    }
    for k, v in hex_args.items():
        if v != defaults[k]:  # user explicitly passed a different value
            cfg[k] = v
    if args.font_title != "Calibri":
        cfg["font_title"] = args.font_title
    if args.font_body != "Calibri":
        cfg["font_body"] = args.font_body

    for label, val in [
        ("accent", cfg.get("accent")),
        ("bg", cfg.get("bg")),
        ("fg", cfg.get("fg")),
    ]:
        try:
            _hex_to_rgb(val)
        except (ValueError, TypeError) as e:
            p.error(f"{label}: {e}")

    if args.out:
        out_dir = Path(args.out)
    else:
        here = Path(__file__).resolve().parent
        out_dir = here.parent / "app" / "templates" / "pptx"

    out_path = generate_template(
        name=args.name,
        bg_hex=cfg["bg"],
        fg_hex=cfg["fg"],
        title_hex=cfg.get("title"),
        accent_hex=cfg["accent"],
        accent2_hex=cfg.get("accent2"),
        font_title=cfg.get("font_title", "Calibri"),
        font_body=cfg.get("font_body", "Calibri"),
        decor=cfg.get("decor", "bars"),
        out_dir=out_dir,
    )
    print(f"template generated: {out_path}")
    print(
        f"  name={args.name!r} bg={cfg['bg']} fg={cfg['fg']} "
        f"accent={cfg['accent']} decor={cfg.get('decor')}"
    )
    print("  slide size: 16:9 widescreen | layouts: 11 | slides: 0")
    print("  theme1.xml: full clrScheme + fontScheme rewritten")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
