"""add image/document fields to messages, add message_id to documents

Revision ID: 2103dfe5a2b5
Revises: 29cdda50fcfd
Create Date: 2026-05-01 17:08:38.478289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2103dfe5a2b5'
down_revision: Union[str, Sequence[str], None] = '29cdda50fcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'messages', ['message_id'], ['id'])
    op.add_column('messages', sa.Column('has_image', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('has_document', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('document_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'document_count')
    op.drop_column('messages', 'image_count')
    op.drop_column('messages', 'has_document')
    op.drop_column('messages', 'has_image')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'message_id')
    # ### end Alembic commands ###
