"""Add thinking, tool_calls, and duration fields to messages

Revision ID: baa4d85745f0
Revises: 2103dfe5a2b5
Create Date: 2026-05-19 11:09:59.823664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa4d85745f0'
down_revision: Union[str, Sequence[str], None] = '2103dfe5a2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thinking', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('thinking_duration', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('generation_duration', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('tool_calls_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_calls_json')
    op.drop_column('messages', 'generation_duration')
    op.drop_column('messages', 'thinking_duration')
    op.drop_column('messages', 'thinking')
    # ### end Alembic commands ###
