"""
use_excel_gen tool — generates an Excel workbook (.xlsx) from a brief.

Architecture:
  0. Deterministic template routing — a small classifier call maps
     well-known requests to built-in templates in the patterns package
     (app/services/patterns/ — one module per pattern; discovered dynamically
     like agent tools). Every formula is generated from the actual
     layout rows in code, so model row-math mistakes are impossible
     for these documents. Unmatched requests continue with the AI path
     below.
  1. Specialized Excel AI LLM call turns (brief, requirements) into a
     strict JSON workbook specification — sheet structure, tables,
     live formulas, charts, notes. See services/excel_gen.py.
  2. The spec is schema-validated (one LLM repair round on failure),
     then converted deterministically by pure openpyxl.
  3. The file is saved to data/reports/{report_id}.xlsx.
  4. The tool returns the file metadata as genResults so the frontend
     renders the deliverable badge with a download link (persisted to
     messages.deliverables by the chat API's _BlockBuilder).

Use cases: compiling web-search results into a spreadsheet, building
sample/concept models with live formulas, formatting user-provided
data into a clean Excel table, or any mix of the above.

Keyword-triggered: "excel", "spreadsheet", "xlsx", "workbook".
"""

from __future__ import annotations

import logging
import time
from typing import Any, Dict, List, Optional

from app.agent.base import BaseTool, ToolCall, ToolResult, ToolType, tool_registry
from app.agent.tools.config_base import (
    ConfigField,
    ToolConfigDefinition,
    register_config,
)
from app.services.excel_gen import generate_spreadsheet

logger = logging.getLogger(__name__)

# Fallbacks when the persisted configuration predates the settings —
# the actual values live in the tool config (Brain ▸ Tools) and are
# read by the service's _llm_limits().
DEFAULT_TIMEOUT_S = 600
DEFAULT_MAX_TOKENS = 8192


def _log(msg: str, *args) -> None:
    try:
        formatted = msg % args if args else msg
    except (TypeError, ValueError):
        formatted = f"{msg} {args}"
    print(f"[excel_gen_tool] {formatted}", flush=True)


class ExcelGenTool(BaseTool):
    """Generate an Excel workbook (.xlsx) from a high-level brief."""

    name = "use_excel_gen"
    display_name = "Excel Generation"
    description = (
        "Generate an Excel spreadsheet (.xlsx) from a brief. "
        "Use when the user asks for an Excel file, spreadsheet, workbook, "
        "or wants data compiled into a table — e.g. turning web-search "
        "results into a clean sheet, building a concept/sample model with "
        "live formulas, or formatting data they provided in the conversation. "
        "Multiple sheets, headers, number formats, live Excel formulas, "
        "charts and a notes sheet are all supported. The workbook is "
        "generated by a specialized spreadsheet AI and saved as a "
        "downloadable file."
    )
    tool_type = ToolType.IMAGE_GEN  # reuse — produces a file deliverable

    param_aliases = {
        # canonical
        "brief": "brief",
        "requirements": "requirements",
        # common synonyms the LLM may emit
        "description": "brief",
        "topic": "brief",
        "query": "brief",
        "task": "brief",
        "constraints": "requirements",
        "instructions": "requirements",
        "specs": "requirements",
    }

    def get_parameters(self) -> dict:
        return {
            "brief": {
                "type": "string",
                "description": (
                    "High-level description of what the spreadsheet should "
                    "contain / achieve. Include any data the user gave "
                    "(numbers, rows, search results) verbatim here."
                ),
            },
            "requirements": {
                "type": "string",
                "description": (
                    "Optional extra constraints: number of sheets, must use "
                    "formulas, specific columns, currency, date ranges, etc."
                ),
            },
        }

    def get_required_params(self) -> List[str]:
        return ["brief"]

    async def execute(
        self,
        *,
        brief: Optional[str] = None,
        requirements: str = "",
        **kwargs,
    ) -> ToolResult:
        """Generate the workbook and return deliverable metadata."""
        start = time.time()
        tool_call = ToolCall(
            id=f"tc-excel-{int(start * 1000)}",
            type=self.tool_type,
            name=self.name,
            status="running",
            title="Generating spreadsheet",
            started_at=start,
        )

        if not brief or not brief.strip():
            tool_call.status = "error"
            tool_call.completed_at = time.time()
            tool_call.error = "Brief cannot be empty"
            return ToolResult(
                success=False,
                output=(
                    "Excel generation failed: brief cannot be empty. "
                    "Provide a 'brief' field describing the spreadsheet."
                ),
                tool_call=tool_call,
            )

        _log(
            "execute START brief=%r requirements=%s",
            brief[:60],
            bool(requirements),
        )

        try:
            # Model override (Brain ▸ Tools) when set, else the service
            # falls back to the Excel task slot (Settings ▸ AI ▸ Models).
            from app.agent.tools import config_store

            model_override = await config_store.tool_model_override(self.name)
            result = await generate_spreadsheet(
                brief=brief.strip(),
                requirements=(requirements or "").strip(),
                model=model_override,
            )

            tool_call.status = "completed"
            tool_call.completed_at = time.time()
            tool_call.gen_results = [
                {
                    "type": "excel",
                    "format": result["format"],
                    "filename": result["filename"],
                    "file_path": result["file_path"],
                    "download_url": result["download_url"],
                    "report_id": result["report_id"],
                    "created_at": result["created_at"],
                    "pattern": result.get("pattern"),
                    "summary": result.get("summary"),
                }
            ]

            # The workbook summary (sheets / tables / charts / live
            # formulas, plus a note when a built-in template was used)
            # travels back to the agent so it can describe the
            # deliverable to the user — same contract as report and
            # pptx generation.
            summary_fragment = result.get("summary") or (
                f"{result.get('sheet_count', 0)} sheets"
            )

            output_msg = (
                f"Excel workbook generated successfully: {result['filename']} "
                f"— {summary_fragment}."
                " The user can download it using the deliverable badge shown in the chat."
                " Tell the user the spreadsheet is ready for download."
            )

            _log(
                "execute DONE brief=%r summary=%s time=%.1fs",
                brief[:60],
                result.get("summary"),
                time.time() - start,
            )

            return ToolResult(
                success=True,
                output=output_msg,
                tool_call=tool_call,
            )

        except Exception as e:
            logger.exception("Excel generation failed: %s", e)
            tool_call.status = "error"
            tool_call.completed_at = time.time()
            tool_call.error = str(e)
            return ToolResult(
                success=False,
                output=f"Excel generation failed: {e}",
                tool_call=tool_call,
            )


# ── Configuration definition (Brain ▸ Tools ▸ Excel Generation) ──


def _validate_excel_custom(custom: Dict[str, Any]) -> Dict[str, Any]:
    """Validate the custom settings; returns the cleaned object."""
    if not isinstance(custom, dict):
        raise ValueError("'custom' must be an object")
    if "timeout_s" in custom and custom["timeout_s"] is not None:
        try:
            v = float(custom["timeout_s"])
        except (TypeError, ValueError):
            raise ValueError("'timeout_s' must be a number")
        if v <= 0 or v > 3600:
            raise ValueError("'timeout_s' must be between 1 and 3600")
        custom["timeout_s"] = int(v)
    if "max_tokens" in custom and custom["max_tokens"] is not None:
        try:
            v = float(custom["max_tokens"])
        except (TypeError, ValueError):
            raise ValueError("'max_tokens' must be a number")
        if v < 1024 or v > 65536:
            raise ValueError("'max_tokens' must be between 1024 and 65536")
        custom["max_tokens"] = int(v)
    return custom


EXCEL_GEN_CONFIG = ToolConfigDefinition(
    tool_name="use_excel_gen",
    display_name="Excel Generation",
    description=(
        "Generate an Excel spreadsheet (.xlsx) from a brief. "
        "Use when the user asks for an Excel file, spreadsheet, workbook, "
        "or wants data compiled into a table — e.g. turning web-search "
        "results into a clean sheet, building a concept/sample model with "
        "live formulas, or formatting data they provided in the conversation. "
        "Multiple sheets, headers, number formats, live Excel formulas, "
        "charts and a notes sheet are all supported. The workbook is "
        "generated by a specialized spreadsheet AI and saved as a "
        "downloadable file."
    ),
    model_task_slot="excel",
    custom_defaults={
        "timeout_s": DEFAULT_TIMEOUT_S,
        "max_tokens": DEFAULT_MAX_TOKENS,
    },
    custom_schema=[
        {
            "key": "generation",
            "label": "Generation",
            "fields": [
                ConfigField(
                    "timeout_s",
                    "Timeout (s)",
                    "int",
                    default=DEFAULT_TIMEOUT_S,
                    help="Per-attempt LLM call timeout for the JSON spec generation",
                ).to_dict(),
                ConfigField(
                    "max_tokens",
                    "Max tokens",
                    "int",
                    default=DEFAULT_MAX_TOKENS,
                    help="Output budget per LLM attempt — big workbooks need more",
                ).to_dict(),
            ],
        },
    ],
    validate_custom=_validate_excel_custom,
)

register_config(EXCEL_GEN_CONFIG)


# Register the tool
tool_registry.register(ExcelGenTool())
logger.info("[excel_gen_tool] ExcelGenTool registered")
