"""
use_excel_gen tool — generates an Excel workbook (.xlsx) from a brief.

Architecture (mirrors use_report_gen / use_pptx_gen):
  1. Specialized Excel AI LLM call turns (brief, requirements) into a
     strict JSON workbook specification — sheet structure, tables,
     live formulas, charts, notes. See services/excel_gen.py.
  2. The spec is schema-validated (one LLM repair round on failure),
     then converted deterministically by pure openpyxl.
  3. The file is saved to data/reports/{report_id}.xlsx.
  4. The tool returns the file metadata as genResults so the frontend
     renders the deliverable badge with a download link (persisted to
     messages.deliverables by the chat API's _BlockBuilder).

Use cases: compiling web-search results into a spreadsheet, building
sample/concept models with live formulas, formatting user-provided
data into a clean Excel table, or any mix of the above.

Keyword-triggered: "excel", "spreadsheet", "xlsx", "workbook".
"""

from __future__ import annotations

import logging
import time
from typing import List, Optional

from app.agent.base import BaseTool, ToolCall, ToolResult, ToolType, tool_registry
from app.services.excel_gen import generate_spreadsheet

logger = logging.getLogger(__name__)


def _log(msg: str, *args) -> None:
    try:
        formatted = msg % args if args else msg
    except (TypeError, ValueError):
        formatted = f"{msg} {args}"
    print(f"[excel_gen_tool] {formatted}", flush=True)


class ExcelGenTool(BaseTool):
    """Generate an Excel workbook (.xlsx) from a high-level brief."""

    name = "use_excel_gen"
    description = (
        "Generate an Excel spreadsheet (.xlsx) from a brief. "
        "Use when the user asks for an Excel file, spreadsheet, workbook, "
        "or wants data compiled into a table — e.g. turning web-search "
        "results into a clean sheet, building a concept/sample model with "
        "live formulas, or formatting data they provided in the conversation. "
        "Multiple sheets, headers, number formats, live Excel formulas, "
        "charts and a notes sheet are all supported. The workbook is "
        "generated by a specialized spreadsheet AI and saved as a "
        "downloadable file."
    )
    tool_type = ToolType.IMAGE_GEN  # reuse — produces a file deliverable

    param_aliases = {
        # canonical
        "brief": "brief",
        "requirements": "requirements",
        # common synonyms the LLM may emit
        "description": "brief",
        "topic": "brief",
        "query": "brief",
        "task": "brief",
        "constraints": "requirements",
        "instructions": "requirements",
        "specs": "requirements",
    }

    def get_parameters(self) -> dict:
        return {
            "brief": {
                "type": "string",
                "description": (
                    "High-level description of what the spreadsheet should "
                    "contain / achieve. Include any data the user gave "
                    "(numbers, rows, search results) verbatim here."
                ),
            },
            "requirements": {
                "type": "string",
                "description": (
                    "Optional extra constraints: number of sheets, must use "
                    "formulas, specific columns, currency, date ranges, etc."
                ),
            },
        }

    def get_required_params(self) -> List[str]:
        return ["brief"]

    async def execute(
        self,
        *,
        brief: Optional[str] = None,
        requirements: str = "",
        **kwargs,
    ) -> ToolResult:
        """Generate the workbook and return deliverable metadata."""
        start = time.time()
        tool_call = ToolCall(
            id=f"tc-excel-{int(start * 1000)}",
            type=self.tool_type,
            name=self.name,
            status="running",
            title="Generating spreadsheet",
            started_at=start,
        )

        if not brief or not brief.strip():
            tool_call.status = "error"
            tool_call.completed_at = time.time()
            tool_call.error = "Brief cannot be empty"
            return ToolResult(
                success=False,
                output=(
                    "Excel generation failed: brief cannot be empty. "
                    "Provide a 'brief' field describing the spreadsheet."
                ),
                tool_call=tool_call,
            )

        _log(
            "execute START brief=%r requirements=%s",
            brief[:60],
            bool(requirements),
        )

        try:
            result = await generate_spreadsheet(
                brief=brief.strip(),
                requirements=(requirements or "").strip(),
            )

            tool_call.status = "completed"
            tool_call.completed_at = time.time()
            tool_call.gen_results = [
                {
                    "type": "excel",
                    "format": result["format"],
                    "filename": result["filename"],
                    "file_path": result["file_path"],
                    "download_url": result["download_url"],
                    "report_id": result["report_id"],
                    "created_at": result["created_at"],
                }
            ]

            output_msg = (
                f"Excel workbook generated successfully: {result['filename']} "
                f"({result.get('sheet_count', 0)} sheets, live formulas preserved)."
                " The user can download it using the deliverable badge shown in the chat."
                " Tell the user the spreadsheet is ready for download."
            )

            _log(
                "execute DONE brief=%r sheets=%s time=%.1fs",
                brief[:60],
                result.get("sheet_count"),
                time.time() - start,
            )

            return ToolResult(
                success=True,
                output=output_msg,
                tool_call=tool_call,
            )

        except Exception as e:
            logger.exception("Excel generation failed: %s", e)
            tool_call.status = "error"
            tool_call.completed_at = time.time()
            tool_call.error = str(e)
            return ToolResult(
                success=False,
                output=f"Excel generation failed: {e}",
                tool_call=tool_call,
            )


# Register the tool
tool_registry.register(ExcelGenTool())
logger.info("[excel_gen_tool] ExcelGenTool registered")
